### ISSUE TITLE
Correct invalid mesh_doctor unit tests + add main test file ?

### ISSUE THREAD

**Issue by alexbenedicto** [GEOS-DEV/geosPythonPackages#42]
Certain current test files of mesh_doctor cannot be run due to invalid absolute path for import.

Do we need to have a main.py test file to launch all test files at once ? @untereiner  @cssherman 

Once done, they can be enabled in CI by @cssherman

**Comment by untereiner** [comment]
Each sub package should have it’s own test directory. You can give a liste of packages to pytest
